
name: CI
on:
  push:
    branches: [ "master" ]
  schedule:
      - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
      
    permissions:
      contents: write

    steps:
    
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: sync  libre fsf la
        run: |
          echo Add other actions to build,
          export mdy=`date`
          git config --local user.email "baiyangwangzhan@hotmail.com"
          git config --local user.name "zhenruyan"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --all
          git remote add libre git://linux-libre.fsfla.org/releases.git
          git fetch libre
          git commit --allow-empty -m "sync libre kernel ${mdy}"
          git push origin --all 
        
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
