
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: sync  libre fsf la
        run: |
          echo Add other actions to build,
          git config --local user.email "baiyangwangzhan@hotmail.com"
          git config --local user.name "zhenruyan"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --all
          git remote set-url libre git://linux-libre.fsfla.org/releases.git
          git fetch libre
          git pull libre --all
          git push origin --all
        
