
name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: sync  libre fsf la
        run: |
          echo Add other actions to build,
          git remote add libre git://linux-libre.fsfla.org/releases.git linux
          git fetch libre
          git pull libre --all
          git push origin --all
